### ISSUE TITLE
Week 1 Project Review

### ISSUE THREAD

**Issue by bonaventureogeto** [Iveynganga/ZINDUA-PYTHON#1]
Hi Ivy, 

Thank you for making your week 1 project submission. 

- Your submission shows a good understanding of control structures, the code structure is simple and easy to follow, making it suitable for a beginner-level project.
- The attempt to use randomization for the computer's choice is good for creating a more dynamic game.

Some growth areas to take note of:

- The variable name random is used both as a module name (import random) and as a variable to store choices for the computer. This is confusing and could lead to unexpected behavior. Consider renaming the variable to something like computer_choices to avoid conflicts.
`computer_choices = ("Rock", "Paper", "Scissors")
`
- The line computerChoice = options[random(0,2)] attempts to use random as a function, but it's actually a module. Change it to random.choice to correctly get a random choice from computer_choices.
`computerChoice = random.choice(computer_choices)
`
- The indentation of the score increment statements is incorrect. They should be inside the corresponding if statements to ensure they are executed only when the conditions are met.
`if userChoice == "Rock" and computerChoice == "Scissors":
    print("You've won")
    user_score += 1
`  
- In the final if-else block, there are typos in variable names (computerscore and userscore). These should be corrected to computer_score and user_score.
`elif computer_score > user_score:
    print('Computer won most rounds!')
`
- Stick to a consistent naming convention for variables. For example, use either snake_case or camelCase. In the code, both conventions are used (userOption and userChoice). Choose one and stick to it.

Overall, great submission. If you could kindly address the above-mentioned issues, I’m confident you’ll nail this task. Remember, getting errors in our code is how we learn.

Happy Coding!

**Comment by bonaventureogeto** [comment]
- Make use of comments to describe your code and make sure your comments are descriptive and detailed enough on what is being implemented.

**Comment by Iveynganga** [comment]
Hi Bonaventure,

I've made the corrections. Please check and let me know.

Thanks.
