### ISSUE TITLE
#regex challenge review

### ISSUE THREAD

**Issue by bonaventureogeto** [Iveynganga/ZINDUA-PYTHON#2]
Hi Ivy,

 I've taken a look at the code you shared, and overall, it's a good start. You have logically organized your code into functions. This promotes modularity and reusability of your code. 

**Some growth areas:**

- The extract_phone_numbers, extract_email_addresses, and replace_email_addresses functions currently have hard-coded examples. Consider modifying these functions to use the provided input parameter string.
- Remove unused variables like replacement and email_addresses inside the functions.
- The regular expression for email addresses is a great start but might need adjustments. Consider using a more robust expression that captures a wider range of valid email formats.
- Remove the print statements inside the functions. Let the caller decide whether to print the results or use them in some other way. Use the return keyword instead.

Excellent submission overall. Feel free to reach out if you have any questions or need further clarification on any point. Keep up the good work!

Happy Coding!

**Comment by Iveynganga** [comment]
Hi Bonaventure,

I've made the corrections. Please check and let me know.

Thanks.
