### ISSUE TITLE
Dictionary Challenge Review

### ISSUE THREAD

**Issue by bonaventureogeto** [Iveynganga/ZINDUA-PYTHON#3]
Hi Ivy,

I've taken a look at your find_highest_priced_product function, and overall, it's a good start! Storing product information in a dictionary is a good choice, providing a structured way to organize data. It also speaks to your understanding of dictionaries and lists. Utilizing a list of dictionaries for product information is a suitable data structure for this scenario.

Some growth areas:

- The function currently lacks implementation to find the highest-priced product. You may want to add logic to iterate through the list of products and identify the one with the highest price.
- The variable my_dict is used to store a list of dictionaries. Consider using a more descriptive name, like products_list to better convey the nature of the variable.
- The current print statement outputs the entire list of products. It would be more useful to print only the product with the highest price. You can achieve this by modifying the print statement after finding the highest-priced product.

Overall, great effort so far. If you could kindly address the above-mentioned issues, I’m confident you’ll meet all the requirements. Remember, getting errors in our code is how we learn.

Looking forward to your resubmission. 

Happy Coding!

**Comment by Iveynganga** [comment]
Hi Bonaventure,

I've made the corrections. Please check and let me know.

Thanks.
