### ISSUE TITLE
Hangman Weekend Project Review

### ISSUE THREAD

**Issue by bonaventureogeto** [Iveynganga/ZINDUA-PYTHON#4]
Hi Ivy,

Thank you for submitting your weekend task. Great work on implementing the Hangman game!

Some areas to work on:

- Given we have looked at file handling, you can consider using a file that contains words that can be used in the hangman game. Also, you can help the user know the letters they have guessed and whether they have guessed the right letters.
- While the code is relatively short, you might want to consider breaking down the logic into functions. This could improve code modularity and make each function more focused on a specific task.
- It might be helpful to include some input validation to ensure that the user's input is a single letter. 

Overall, great submission.

Happy Coding!

**Comment by Iveynganga** [comment]
Hi Bonaventure,

I've made the corrections. Please check and let me know.

Thanks.
