### ISSUE TITLE
rick and morty review

### ISSUE THREAD

**Issue by bonaventureogeto** [Iveynganga/ZINDUA-PYTHON#5]
**Some aspects I liked about your code:**

- Your script includes three functions aimed at fetching data from the Rick and Morty API: characters, locations, and episodes. It's great to see you making use of the requests library for API calls and starting to structure your code with clear function names.
- Function names are descriptive, which is good practice. However, the Python style guide (PEP 8) recommends using snake_case for function names, so fetch_characters, fetch_locations, and fetch_episodes are correctly named according to this convention.

**Growth areas:**

- Your functions are set up to fetch data from the Rick and Morty API but don't actually process the API response beyond making the request.
- The arrays characters, locations, and episodes are initialized with [20], which seems intended to hold a count but is not used to store or calculate any data from the responses.
- Your code lacks comments or docstrings, which are essential for documentation. Adding these would make your code more understandable to others and to your future self.
- To actually fetch and display the number of characters, locations, and episodes, you need to process the response object returned by requests.get(url). Use response.json() to parse the JSON data.

Overall, you've made a good start. With a few adjustments for data processing, style consistency, and adding documentation, your code will be more efficient, understandable, and robust. Keep up the great work!

**Comment by Iveynganga** [comment]
Hi Bonaventure,

I've made the corrections. Please check and let me know.

Thanks.
